### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by jbfriedrich** [proficientdesigners/sublime-text-bs4-autocomplete#1]
I successfully installed the package with "Package Control", but the autocompletion does not work at all. The bootstrap classes are not offered when I am inside `class=""`. I tried handlebar and html files. My Sublime Text version is 3.2.1 (build 3207),

I also have the [Boostrap 4.3 snippets](https://github.com/proficientdesigners/sublime-text-bs4-snippets) installed, which works fine!

**Comment by karthi-ansidhovi** [comment]
Hey @jbfriedrich , thank you for letting us know, we're working on it to resolve the issue...

**Comment by proficientdesigners** [comment]
@jbfriedrich thanks for pin pointing the issue, we're working on it, soon we'll resolve this issue. Stay Put.

**Comment by jbfriedrich** [comment]
Thats awesome! Thanks for the quick reply, much appreciated!

**Comment by jbfriedrich** [comment]
It seems to work fine now with version 1.0.3! Thank you so much for fixing the issue that quickly!
